name: Crystal CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '* */23 * * SUN'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: cd tests/general && shards install && CRYSTAL_ENV=TEST crystal spec e2e/* --error-trace
