name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Enter test dir
      run: cd tests/general
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: CRYSTAL_ENV=TEST crystal spec e2e/ --error-trace
